apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: ecsdemo-nodejs 
  labels:
    apps.tanzu.vmware.com/workload-type: argo-gitops-supply-chain
spec:
  source:
    git:
      ref:
        branch: main  
      url: https://github.com/terasky-int/ecsdemo-nodejs.git
      